# ---
# - name: Pull Docker Image from Docker Hub
#   hosts: localhost
#   remote_user: nikhil
#   become: false
#   tasks:
#     - name: Pull Docker Image
#       docker_image:
#         name: "nikhiliiitb/scientific_calculator"
#         source: pull
#       register: docker_pull_result

#     - name: Display Docker Pull Result
#       debug:
#         var: docker_pull_result
        
#     - name: Start Docker service
#       service:
#         name: docker
#         state: started
#     - name: Running container
#       shell: docker run -it -d --name scientific_calculator nikhiliiitb/scientific_calculator


---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: nikhil
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "nikhiliiitb/scientific_calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Stop and remove existing container if present and running
      shell: docker stop scientific_calculator && docker rm scientific_calculator
      ignore_errors: true

    - name: Start Docker service
      service:
        name: docker
        state: started


    - name: Running container
      # shell: docker run -it -d --name scientific_calculator nikhiliiitb/scientific_calculator
      shell: docker create -it --name scientific_calculator nikhiliiitb/scientific_calculator

